In [1]:
import sqlite3
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error
from math import sqrt
from datetime import datetime

In [2]:
cnx=sqlite3.connect('database.sqlite')
player_data=pd.read_sql_query("SELECT * FROM Player_Attributes",cnx)
player_data.head()

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [4]:
player_data.shape

(183978, 42)

In [6]:
player_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183978 entries, 0 to 183977
Data columns (total 42 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   183978 non-null  int64
 1   player_fifa_api_id   183978 non-null  int64
 2   player_api_id        183978 non-null  int64
 3   date                 183978 non-null  object
 4   overall_rating       183142 non-null  float64
 5   potential            183142 non-null  float64
 6   preferred_foot       183142 non-null  object
 7   attacking_work_rate  180748 non-null  object
 8   defensive_work_rate  183142 non-null  object
 9   crossing             183142 non-null  float64
 10  finishing            183142 non-null  float64
 11  heading_accuracy     183142 non-null  float64
 12  short_passing        183142 non-null  float64
 13  volleys              181265 non-null  float64
 14  dribbling            183142 non-null  float64
 15  curve                181265 non-null  float64
 16  free_kick_accuracy   183142 non-null  float64
 17  long_passing         183142 non-null  float64
 18  ball_control         183142 non-null  float64
 19  acceleration         183142 non-null  float64
 20  sprint_speed         183142 non-null  float64
 21  agility              181265 non-null  float64
 22  reactions            183142 non-null  float64
 23  balance              181265 non-null  float64
 24  shot_power           183142 non-null  float64
 25  jumping              181265 non-null  float64
 26  stamina              183142 non-null  float64
 27  strength             183142 non-null  float64
 28  long_shots           183142 non-null  float64
 29  aggression           183142 non-null  float64
 30  interceptions        183142 non-null  float64
 31  positioning          183142 non-null  float64
 32  vision               181265 non-null  float64
 33  penalties            183142 non-null  float64
 34  marking              183142 non-null  float64
 35  standing_tackle      183142 non-null  float64
 36  sliding_tackle       181265 non-null  float64
 37  gk_diving            183142 non-null  float64
 38  gk_handling          183142 non-null  float64
 39  gk_kicking           183142 non-null  float64
 40  gk_positioning       183142 non-null  float64
 41  gk_reflexes          183142 non-null  float64
dtypes: float64(35), int64(3), object(4)
memory usage: 59.0+ MB

In [38]:
numerical_player_data=[feature for feature in player_data.columns if player_data[feature].dtype!='O']
print(numerical_player_data)
categorical_player_data=[feature for feature in player_data.columns if player_data[feature].dtype=='O']
print(categorical_player_data)

['id', 'player_fifa_api_id', 'player_api_id', 'overall_rating', 'potential', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'free_kick_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'marking', 'standing_tackle', 'sliding_tackle', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes']
['date', 'preferred_foot', 'attacking_work_rate', 'defensive_work_rate']

In [22]:
player_data.isnull().sum()

id                        0
player_fifa_api_id        0
player_api_id             0
date                      0
overall_rating          836
potential               836
preferred_foot          836
attacking_work_rate    3230
defensive_work_rate     836
crossing                836
finishing               836
heading_accuracy        836
short_passing           836
volleys                2713
dribbling               836
curve                  2713
free_kick_accuracy      836
long_passing            836
ball_control            836
acceleration            836
sprint_speed            836
agility                2713
reactions               836
balance                2713
shot_power              836
jumping                2713
stamina                 836
strength                836
long_shots              836
aggression              836
interceptions           836
positioning             836
vision                 2713
penalties               836
marking                 836
standing_tackle         836
sliding_tackle         2713
gk_diving               836
gk_handling             836
gk_kicking              836
gk_positioning          836
gk_reflexes             836
dtype: int64

In [24]:
player_data.dropna(thresh=5,inplace=True)

In [25]:
player_data.shape

(183142, 42)

In [27]:
target_data=player_data['overall_rating']
target_data

0         67.0
1         67.0
2         62.0
3         61.0
4         61.0
          ...
183973    83.0
183974    78.0
183975    77.0
183976    78.0
183977    80.0
Name: overall_rating, Length: 183142, dtype: float64

In [71]:
from Clean_and_Merge import Clean_and_Merge
custom_attribute_object=Clean_and_Merge()

merged_player_data=custom_attribute_object.fit_transform(player_data)
merged_player_data.head()

TypeError: __init__() should return None, not 'Clean_and_Merge'

,id,player_fifa_api_id,player_api_id,overall_rating,potential,crossing,finishing,heading_accuracy,short_passing,volleys,...,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,date,preferred_foot,attacking_work_rate,defensive_work_rate
0,3.0,218353.0,505942.0,63.600000,67.600000,48.600000,43.600000,70.600000,60.600000,43.600000,...,67.800000,5.600000,10.600000,9.600000,7.600000,7.600000,2007-02-22 00:00:00,right,medium,medium
1,22.0,189615.0,155782.0,66.969697,74.484848,70.787879,49.454545,52.939394,62.272727,29.151515,...,71.515152,12.181818,8.666667,14.242424,10.363636,12.909091,2007-02-22 00:00:00,left,medium,medium
2,51.5,186170.0,162549.0,67.000000,74.192308,68.115385,57.923077,58.692308,65.115385,54.269231,...,21.346154,14.038462,11.807692,17.730769,10.115385,13.500000,2007-02-22 00:00:00,right,medium,medium
3,76.0,140161.0,30572.0,69.086957,70.782609,57.217391,26.260870,69.260870,64.695652,47.782609,...,68.043478,14.173913,11.173913,22.869565,11.173913,10.173913,2007-02-22 00:00:00,right,medium,medium
4,100.0,17725.0,23780.0,73.240000,74.680000,45.080000,38.840000,73.040000,64.760000,32.080000,...,74.600000,8.280000,8.320000,24.920000,12.840000,11.920000,2007-02-22 00:00:00,right,medium,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11055,183931.0,2488.0,26357.0,74.384615,75.461538,42.000000,27.000000,75.153846,70.000000,30.000000,...,72.692308,12.846154,12.769231,25.461538,11.384615,13.615385,2007-02-22 00:00:00,right,low,medium
11056,183945.5,164680.0,111182.0,65.687500,71.625000,67.250000,46.750000,60.312500,63.125000,54.562500,...,63.875000,9.000000,8.000000,5.000000,5.000000,8.000000,2007-02-22 00:00:00,left,medium,medium
11057,183957.0,111191.0,36491.0,67.571429,72.857143,63.142857,44.571429,59.857143,66.857143,57.000000,...,59.000000,7.142857,18.714286,42.428571,16.714286,16.714286,2007-02-22 00:00:00,left,NaN,_0
11058,183964.5,47058.0,35506.0,70.750000,78.125000,46.750000,43.000000,79.000000,58.875000,59.000000,...,65.000000,14.000000,18.500000,41.625000,19.000000,20.000000,2007-02-22 00:00:00,right,NaN,_0
11059,183973.5,102359.0,39902.0,80.000000,81.700000,78.200000,72.600000,57.400000,85.500000,77.000000,...,30.000000,9.000000,15.400000,42.100000,16.200000,12.000000,2007-02-22 00:00:00,right,medium,low

In [64]:
        low_class=['0','1','2']
        medium_class=['3','4','5','6']
        high_class=['7','8','9']

        for i in low_class:
            new_df['defensive_work_rate'].replace(i,'low',inplace=True)

        for i in medium_class:
            new_df['defensive_work_rate'].replace(i,'medium',inplace=True)

        for i in high_class:
            new_df['defensive_work_rate'].replace(i,'high',inplace=True)

defensive_work_rate
medium    7781
high      1337
low       1006
_0         540
o          278
ormal       66
ean         21
es          16
tocky       15
Name: count, dtype: int64

Index(['date', 'preferred_foot', 'attacking_work_rate', 'defensive_work_rate'], dtype='object')